# Generated by Django 4.2.2 on 2023-06-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(max_length=50)),
                ('myGender', models.IntegerField()),
                ('myBirth', models.DateField()),
                ('myHeight', models.FloatField()),
                ('myWeight', models.FloatField()),
            ],
        ),
    ]
