# Generated by Django 4.2.2 on 2023-06-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_mygender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='myHeight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='myWeight',
            field=models.IntegerField(),
        ),
    ]
